# Generated by Django 4.1.6 on 2023-09-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Management_system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_management",
            name="Student_id",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="student_management",
            name="year",
            field=models.TextField(max_length=4),
        ),
    ]
