# Generated by Django 4.1.6 on 2023-09-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Management_system", "0003_rename_student_id_student_management_student_adm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student_management",
            name="Student_adm",
        ),
        migrations.AddField(
            model_name="student_management",
            name="Student_Adm",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
