# Generated by Django 4.2.6 on 2023-11-01 09:16

import Management_system.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Management_system", "0004_remove_student_management_student_adm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_management",
            name="image",
            field=models.ImageField(
                null=True, upload_to=Management_system.models.filepath
            ),
        ),
    ]
